# Generated by Django 4.0.4 on 2022-08-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0002_productprice_enddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprice',
            name='productId',
        ),
        migrations.AddField(
            model_name='productprice',
            name='productName',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
